## Data Manipulation

The proces of changing, organizing, or transforming data to make it more useful, readable, or suitable for analysis.

## Pandas

- Pandas handles data structure, filtering, sorting or grouping or calculating new values from existing data
- Pandas is used for working with data. Helps load, clean, analyze, and manipulate data easily.

### Key Concepts
- Series: A single column of data (Like a list of labels)
- Labels: Labels from rows, helping you identify and access data

In [1]:
import pandas as pd

### DataFrame 

A DataFrame is like a table with rows and columns

In [19]:
# Create a Dictionary with sample data
data = {
    'coin': ['Bitcoin', 'Ethereum', 'Litecoin'],
    'price': [45000, 3000, 150],
    'volume': [1000000, 500000, 200000]
}

df = pd.DataFrame(data)

print(df)

       coin  price   volume
0   Bitcoin  45000  1000000
1  Ethereum   3000   500000
2  Litecoin    150   200000

### Data Exploration

In [4]:
df.head()  # Display the first few rows of the DataFrame

       coin  price   volume
0   Bitcoin  45000  1000000
1  Ethereum   3000   500000
2  Litecoin    150   200000

In [5]:
df.tail()  # Display the last few rows of the DataFrame

       coin  price   volume
0   Bitcoin  45000  1000000
1  Ethereum   3000   500000
2  Litecoin    150   200000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   coin    3 non-null      object
 1   price   3 non-null      int64
 2   volume  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [10]:
# Select a specific column

df['coin']  # Access the 'coin' column

0     Bitcoin
1    Ethereum
2    Litecoin
Name: coin, dtype: object

In [11]:
# Fetching two columns

df[['coin', 'price']]  # Access the 'coin' and 'price' columns

       coin  price
0   Bitcoin  45000
1  Ethereum   3000
2  Litecoin    150

In [12]:
# Filtering rows based on a condition

df[df['price'] > 1000]  # Filter rows where price is greater than 1000

       coin  price   volume
0   Bitcoin  45000  1000000
1  Ethereum   3000      nan

In [15]:
# Sorting -> sort columns in ascending or descending order

df.sort_values('price') # Sorts in ascending order by default

       coin  price   volume
2  Litecoin    150   200000
1  Ethereum   3000      nan
0   Bitcoin  45000  1000000

In [16]:
df.sort_values('price', ascending = False) # To sort in descending order

       coin  price   volume
0   Bitcoin  45000  1000000
1  Ethereum   3000      nan
2  Litecoin    150   200000

In [21]:
# Adding a new column -> Price after 2% change

df['Price_after_2pct'] = df['price'] * 1.02
df

       coin  price   volume  Price_after_2pct
0   Bitcoin  45000  1000000           45900.0
1  Ethereum   3000   500000            3060.0
2  Litecoin    150   200000             153.0

In [ ]:
df.describe() # Used to investigate

             price  Price_after_2pct
count      3.00000          3.000000
mean   16050.00000      16371.000000
std    25111.89957      25614.137561
min      150.00000        153.000000
25%     1575.00000       1606.500000
50%     3000.00000       3060.000000
75%    24000.00000      24480.000000
max    45000.00000      45900.000000

In [22]:
# Save and Load data

#Saving to CSV file
df.to_csv('crypto_data.csv', index=False)

## Numpy

- Useful for working with arrays (lists of numbers) and performing fast mathematical operations

- Numpy -> Array
- Pandas -> Dataframe

In [23]:
import numpy as np

In [26]:
prices = np.array([45000, 50000, 40000, 20000])

print(prices)

[45000 50000 40000 20000]

In [ ]:
# To know the number of elements

prices.shape

(4,)

In [31]:
# Data Type check

print(prices.dtype)

int64

In [35]:
# adding 1000 to all the prices in the array

prices_plus_100 = prices + 100

print(prices_plus_100)

[45100 50100 40100 20100]

In [36]:
# Computing for 2% increase in price 

price_increase = prices_plus_100 + 1.02
print(price_increase)

[45101.02 50101.02 40101.02 20101.02]

In [37]:
# Filtering through the array

higher_price = price_increase[price_increase > 30000]
print(higher_price)

[45101.02 50101.02 40101.02]

In [43]:
# Basic statistical functions

volume = np.array([500000, 300000, 700000, 100000])

print("\nStatistics for Volume:")

print("Mean Average: ", np.mean(volume)) # Average volume
print("Minimum: ", np.min(volume)) # Minimum Volume
print("Maximum: ", np.max(volume)) # Maximum Volume
print("Sum: ", np.sum(volume)) # Total Sum of Volume
print("STD (Volatility): ", np.std(volume))

Statistics for Volume:
Mean Average:  400000.0
Minimum:  100000
Maximum:  700000
Sum:  1600000
STD (Volatility):  223606.79774997896

In [45]:
# Working with a 2D Array

crypto_data = np.array([
    [45000, 50000],
    [33000, 60000],
    [12000, 40000]
])

print(crypto_data)

[[45000 50000]
 [33000 60000]
 [12000 40000]]

In [46]:
# Access row

crypto_data[1]

array([33000, 60000])

In [51]:
# Acess column

print(crypto_data[1:,0]) # row 2, column 1
print(crypto_data[:, 1]) # Column 2

[33000 12000]
[50000 60000 40000]